import 'package:ncmdump/src/model/artist.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Meta {
/*
{
  "format": "flac",
  "musicId": 26112101,
  "musicName": "いつかどこかで (Album Version)",
  "artist": [
    [
      "□□□(クチロロ)", 1231231
    ]
  ],
  "album": "マンパワー",
  "albumId": 2389206,
  "albumPicDocId": 18545462627518744,
  "albumPic": "http://p1.music.126.net/xQ8-zNYuS4-6RDIubGDGSQ==/18545462627518744.jpg",
  "mvId": 0,
  "flag": 261,
  "bitrate": 1013110,
  "duration": 831000,
  "gain": -12.327300071716309,
  "alias": [
    ""
  ],
  "transNames": [
    "哪天在某处再会"
  ]
} 
*/

  String? format;
  int? musicId;
  String? musicName;
  List<Artist?>? artist;
  String? album;
  int? albumId;
  int? albumPicDocId;
  String? albumPic;
  int? mvId;
  int? flag;
  int? bitrate;
  int? duration;
  double? gain;
  List<String?>? alias;
  List<String?>? transNames;

  Meta({
    this.format,
    this.musicId,
    this.musicName,
    this.artist,
    this.album,
    this.albumId,
    this.albumPicDocId,
    this.albumPic,
    this.mvId,
    this.flag,
    this.bitrate,
    this.duration,
    this.gain,
    this.alias,
    this.transNames,
  });
  Meta.fromJson(Map<String, dynamic> json) {
    format = json['format']?.toString();
    musicId = json['musicId']?.toInt();
    musicName = json['musicName']?.toString();
    if (json['artist'] != null) {
      final v = json['artist'];
      final arr0 = <Artist>[];
      v.forEach((v) {
        arr0.add(Artist.fromJson(v));
      });
      artist = arr0;
    }
    album = json['album']?.toString();
    albumId = json['albumId']?.toInt();
    albumPicDocId = json['albumPicDocId']?.toInt();
    albumPic = json['albumPic']?.toString();
    mvId = json['mvId']?.toInt();
    flag = json['flag']?.toInt();
    bitrate = json['bitrate']?.toInt();
    duration = json['duration']?.toInt();
    gain = json['gain']?.toDouble();
    if (json['alias'] != null) {
      final v = json['alias'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      alias = arr0;
    }
    if (json['transNames'] != null) {
      final v = json['transNames'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      transNames = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['format'] = format;
    data['musicId'] = musicId;
    data['musicName'] = musicName;
    if (artist != null) {
      final v = artist;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['artist'] = arr0;
    }
    data['album'] = album;
    data['albumId'] = albumId;
    data['albumPicDocId'] = albumPicDocId;
    data['albumPic'] = albumPic;
    data['mvId'] = mvId;
    data['flag'] = flag;
    data['bitrate'] = bitrate;
    data['duration'] = duration;
    data['gain'] = gain;
    if (alias != null) {
      final v = alias;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['alias'] = arr0;
    }
    if (transNames != null) {
      final v = transNames;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['transNames'] = arr0;
    }
    return data;
  }
}
